/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SporcuKartOyunu;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Collections;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gökçe Yılmaz
 */
public class AnaMenu extends javax.swing.JFrame {
     String kullaniciAdi;
   
    /**
     * Creates new form AnaMenu
     */
    public AnaMenu() {
        initComponents();
        
        isimGir.setVisible(false);
        oyunAdi.setVisible(true);
        jLabel2.setVisible(false);
        
         
        
    }
     public AnaMenu(String kullaniciAdi){
     this.kullaniciAdi=kullaniciAdi;
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        oyunAdi = new javax.swing.JLabel();
        isimGir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1071, 671));
        setPreferredSize(new java.awt.Dimension(100, 373));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("İsim Giriniz:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 440, 110, 40);

        oyunAdi.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        oyunAdi.setForeground(new java.awt.Color(255, 255, 255));
        oyunAdi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oyunAdi.setText("SPORCU KART OYUNU");
        getContentPane().add(oyunAdi);
        oyunAdi.setBounds(250, 110, 580, 80);

        isimGir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        isimGir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isimGir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isimGirActionPerformed(evt);
            }
        });
        getContentPane().add(isimGir);
        isimGir.setBounds(480, 440, 140, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArkaPlan/play1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 300, 310, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArkaPlan/arkaPlan1.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(920, 580));
        jLabel1.setMinimumSize(new java.awt.Dimension(920, 580));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1080, 670);

        jPanel1.setMaximumSize(new java.awt.Dimension(920, 580));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setVisible(false);
        isimGir.setVisible(true);
         jLabel2.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void isimGirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isimGirActionPerformed
        
        
        
        
        if(isimGir.getText().isEmpty()){
        JLabel message=new JLabel("Lütfen bir isim giriniz!!!");
        message.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null, message);
        }
        else{
         kullaniciAdi=isimGir.getText();
         
         
           
            
                
        
        
        this.setVisible(false);
       Test oyunekrani= new Test();
       oyunekrani.setVisible(true);
       Test.oyuncuAdi.setText(""+kullaniciAdi);
            
        
        
        }
        
    }//GEN-LAST:event_isimGirActionPerformed

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField isimGir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel oyunAdi;
    // End of variables declaration//GEN-END:variables
}
